theme: jekyll-theme-cayman
title: Wire Detection using Synthetic Data and Dilated Convolutional Networks for Unmanned Aerial Vehicles
description: Project page for our IROS 2017 paper. Code release coming soon!
